# Generated by Django 3.1.6 on 2021-05-30 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_connectedusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectedusers',
            name='username',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
